### ISSUE TITLE
Required value geen default?

### ISSUE THREAD

**Issue by rory-vds** [remypar5/mtg-lifecounter#13]
https://github.com/remypar5/mtg-lifecounter/blob/9194a47427c92d3ab239f8fd3f071034a4907cc2/js/components/NumberSpinner.js#L71

Ik zou voor alle geschreven propTypes een defaultProps neerzetten, zeker wanneer een propType required is.

Zo programmeer je je app defensive en heb je minder kans op nullpointers.

**Comment by remypar5** [comment]
Waarom zou je default waarden bepalen voor required properties? Door een default te definiëren is hij per definitie niet meer required.

**Comment by rory-vds** [comment]
Ja, oops ik zie dat wij dat ook niet gebruiken voor required proptypes, het ging mij meer om de non-required proptypes: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md 
Dus de andere min/max etc proptypes wel.

**Comment by remypar5** [comment]
Gedaan met #14
