### ISSUE TITLE
Destructuring assignment

### ISSUE THREAD

**Issue by rory-vds** [remypar5/mtg-lifecounter#8]
https://github.com/remypar5/mtg-lifecounter/blob/9194a47427c92d3ab239f8fd3f071034a4907cc2/js/components/NumberSpinner.js#L19

Destructuring assignment vind ik 1 van de fijne changes in ES6, het is een 'syntactical sugar', maar ik vind het wel wat hebben qua leesbaarheid en ook qua dryness.
```

 const props = this.props;
        return (
            <View style={styles.container}>
                <SpinnerButton
                    style={ styles.button }
                    width="20%"
                    content="-"
                    onPress={() => this.decrease(props.step)}
                    onHold={() => this.decrease(props.stepLarge)} />
                <Text style={styles.value}>{this.state.value}</Text>
                <SpinnerButton
                    width="20%"
                    style={ styles.button }
                    content="+"
                    onPress={() => this.increase(props.step)}
                    onHold={() => this.increase(props.stepLarge)} />
            </View>
        );

```
Zou ik dit doen:

```
const { step, stepLarge } = this.props;
const { container, button } = styles;

<SpinnerButton
    onPress={() => this.decrease(step)}
    style={ button }
```
Voordeel is dat je niet steeds this.props of props overal hoeft neer te zetten.
Maar ook dat je in de destructuring kan zien wat je uit de props haalt mbt 'treeshaking'. Vooral wanneer je veel props/styles/state gaat hebben, gaat dit de leesbaarheid bevorderen.

**Comment by remypar5** [comment]
Gedaan met #14
