### ISSUE TITLE
Zou ik ook destructuring gebruiken.

### ISSUE THREAD

**Issue by rory-vds** [remypar5/mtg-lifecounter#9]
https://github.com/remypar5/mtg-lifecounter/blob/9194a47427c92d3ab239f8fd3f071034a4907cc2/js/components/Player.js#L20

Nogmaals met destructuring assignment, zou ik het zo opzetten. Vind ik super leesbaar.

```
const { player } = this.props;
const { color, name } = player;
const { gameOver, life } = this.state;
const { tile, gameOver: gameOverStyle, playerName } = styles;

<View style={ [tile, gameOver ? gameOverStyle : null] }>
                <NumberSpinner value={ life }
                    onChange={this.onLifeChange} />
                <Text style={ [playerName, { color: color }] }>{ name }</Text>
            </View>
```

Het gedeelte met `gameOver: gameOverStyle` kun je zien als destructuring en new variable name geven, omdat we al een 'gameOver' variable in de state hebben. De variabelen komen natuurlijk overeen met de property names in het object.

**Comment by remypar5** [comment]
Gedaan met #14
